all: research optimization

research: Hash_research.c Hash_Table.c List.c
	gcc Hash_research.c Hash_Table.c List.c -o ..\Hash_research.exe
	

optimization: Hash_optimization.c Hash_Table.c List.c
	gcc -O0 Hash_optimization.c Hash_Table.c List.c -o ..\Hash_optimization.exe